# SPDX-License-Identifier: MIT
augur_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('AUGUR_DB_HOST', 'localhost') }}"
      user: "{{ env_var('AUGUR_DB_USER', 'augur') }}"
      password: "{{ env_var('AUGUR_DB_PASSWORD', 'password123') }}"
      port: "{{ env_var('AUGUR_DB_PORT', '5432') | int }}"
      dbname: "{{ env_var('AUGUR_DB_NAME', 'augur') }}"
      schema: "{{ env_var('AUGUR_DB_SCHEMA', 'public') }}"
      threads: 4
